baronbale_website/baronbale_website/checker/urls.py
from django.conf.urls import url

from . import views

app_name = 'checker'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^correct$', views.correct, name='correct'),
    url(r'^incorrect$', views.incorrect, name='incorrect'),
]

baronbale_website/baronbale_website/gc_toolbox/urls.py
from django.conf.urls import url

from . import views_cesar, views_polybius, views_lettervalues, views_base64
from .views import BannerCollectorView

app_name = 'gc_toolbox'
urlpatterns = [
    url(r'^base64/$', views_base64.index, name='base64'),
    url(r'^base64/encode/file/$', views_base64.encode_file, name='base64_encode_file'),
    url(r'^base64/encode/text/$', views_base64.encode_text, name='base64_encode_text'),
    url(r'^base64/decode/$', views_base64.decode, name='base64_decode'),

    url(r'^cesar/$', views_cesar.index, name='cesar'),
    url(r'^cesar/encrypt/$', views_cesar.encrypt, name='cesar_encrypt'),
    url(r'^cesar/decrypt/$', views_cesar.decrypt, name='cesar_decrypt'),

    url(r'^lettervalues/$', views_lettervalues.letter_value_calculator, name='lettervalues'),

    url(r'^polybius/$', views_polybius.index, name='polybius'),
    url(r'^polybius/encrypt/$', views_polybius.encrypt, name='polybius_encrypt'),
    url(r'^polybius/decrypt/$', views_polybius.decrypt, name='polybius_decrypt'),

    url(r'banner/$', BannerCollectorView.BannerCollectorView.as_view(), name="banner_collector"),
]

baronbale_website/baronbale_website/lab/urls.py
from django.conf.urls import url

from . import views

app_name = 'lab'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^json/$', views.display_json, name='json'),
]

baronbale_website/baronbale_website/staticpages/urls.py
from django.conf.urls import url

from . import views

app_name = 'staticpages'
urlpatterns = [
    url(r'contribute/$', views.Contribute.as_view(), name='contribute'),
    url(r'imprint/$', views.Imprint.as_view(), name='imprint'),
    url(r'privacy/$', views.PrivacyPolicy.as_view(), name='privacy'),
    url(r'roadmap/$', views.Roadmap.as_view(), name='roadmap'),
]

baronbale_website/baronbale_website/toolbox/urls.py
from django.conf.urls import url

from . import views

app_name = 'toolbox'
urlpatterns = (
    url(r'duplicateremover/', views.duplicate_remover, name='duplicate_remover'),
)

baronbale_website/baronbale_website/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

urlpatterns = i18n_patterns(
    url(r'^tools/gc/', include('baronbale_website.gc_toolbox.urls')),
    url(r'^tools/', include('baronbale_website.toolbox.urls')),
    url(r'^', include('baronbale_website.homepage.urls')),
    url(r'^o_pulchram_avem/', include('baronbale_website.checker.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('baronbale_website.staticpages.urls'))
)

urlpatterns += [
                   url(r'^i18n/', include('django.conf.urls.i18n')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'staticpages.views.error404'

baronbale_website/baronbale_website/checker/models.py
from django.db import models

# Create your models here.

baronbale_website/baronbale_website/downloads/models.py
from django.db import models
from django.utils.translation import ugettext as _


class Cache(models.Model):
    cache_id = models.CharField(_('Cache-ID'))
    name = models.CharField(_('Cache-Name'))

    def get_all_images(self):
        return DownloadFile.objects.filter(cache=self)


class DownloadFile(models.Model):
    name = models.CharField(_('name'))
    download_file = models.FileField(_('Download-File'), upload_to='downloads/')
    cache = models.ForeignKeyField(
        Cache,
        models.CASCADE,
        null=False,
        blank=False
    )

baronbale_website/baronbale_website/gc_toolbox/models.py
from django.db import models


class CacheCoordinates(models.Model):
    gc_code = models.CharField(max_length=10)
    latitude = models.CharField(max_length=15)
    longitude = models.CharField(max_length=15)
    type = models.CharField(max_length=30, null=True)

    class Meta:
        unique_together = (('gc_code', 'latitude', 'longitude'),)


class BannerDimension(models.Model):
    banner = models.CharField(max_length=64)
    ratio = models.FloatField(default=0.0)
    width = models.IntegerField()
    height = models.IntegerField()


class SpecialBanner(models.Model):
    gc_code = models.CharField(max_length=10)
    image_url = models.CharField(max_length=255, null=True, blank=True)
    reason = models.CharField(max_length=100)

    def __str__(self):
        return self.gc_code

baronbale_website/baronbale_website/homepage/models.py
from django.db import models

# Create your models here.

baronbale_website/baronbale_website/initializer/models.py
from django.db import models

# Create your models here.

baronbale_website/baronbale_website/lab/models.py
from django.db import models

# Create your models here.

baronbale_website/baronbale_website/staticpages/models.py
from django.db import models

# Create your models here.

baronbale_website/baronbale_website/toolbox/models.py
from django.db import models

# Create your models here.

baronbale_website/baronbale_website/downloads/forms.py
from django.utils.translation import ugettext as _
from django import forms

baronbale_website/baronbale_website/gc_toolbox/forms.py
from django.utils.translation import ugettext as _
from django import forms


def get_cesar_cipher_choices(include_all):
    choices = []
    if include_all:
        choices += [(0, _('all'))]
    for idx in range(1, 26):
        choices += [(idx, idx)]
    return choices


class CesarCipherEncryptForm(forms.Form):
    plain_message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )

    key = forms.ChoiceField(
        label=_('Key'),
        choices=get_cesar_cipher_choices(False),
        initial=13
    )


class CesarCipherDecryptForm(forms.Form):
    cipher_message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )

    key = forms.ChoiceField(
        label=_('Key'),
        choices=get_cesar_cipher_choices(True),
        initial=0
    )


class PolybiusCipherForm(forms.Form):
    message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )


class LetterValueCalculatorForm(forms.Form):
    options = (
        ('1', 'A=01, ..., Z=26'),
        ('2', 'A=26, ..., Z=01'),
    )

    message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )

    extra_values = forms.CharField(
        label=_('Extra Values'),
        widget=forms.Textarea,
        required=False
    )

    direction = forms.ChoiceField(
        label=_('Direction'),
        choices=options
    )

    offset = forms.IntegerField(
        label=_('Offset'),
        initial=0
    )

    include_numeric = forms.BooleanField(
        label=_('Include numeric values'),
        required=False
    )


class Base64EncodeFileForm(forms.Form):
    file_to_encode = forms.FileField(
        label=_('File to encode')
    )


class Base64EncodeTextForm(forms.Form):
    message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )


class Base64DecodeForm(forms.Form):
    message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )

    is_file = forms.BooleanField(
        label=_('Is a file'),
        required=False
    )


class UploadGPXForm(forms.Form):
    banner_file = forms.FileField(
        label=_('GPX- or zip-File')
    )
    horizontal_banners_per_row = forms.IntegerField(
        label=_('Horizontal banners per row'),
        min_value=1,
        initial=2
    )
    vertical_banners_per_row = forms.IntegerField(
        label=_('Vertical banners per row'),
        min_value=1,
        initial=3
    )

baronbale_website/baronbale_website/toolbox/forms.py
from django.utils.translation import ugettext as _
from django import forms


class DuplicateRemoverForm(forms.Form):
    new_items = forms.CharField(
        label=_('Items to clean'),
        widget=forms.Textarea
    )

    old_items = forms.CharField(
        label=_('Already existing Items'),
        widget=forms.Textarea
    )

baronbale_website/baronbale_website/checker/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def index(request):
    if request.method == 'POST':

        checker_code = request.POST.get('ccode')
        checker_code = checker_code.strip().lower()
        if checker_code == 'h gis fis e fis gis' or checker_code == "h'' gis'' fis'' e'' fis'' gis''" or checker_code == 'h" gis" fis" e" fis" gis"':
            return HttpResponseRedirect(reverse('checker:correct'))
        else:
            return HttpResponseRedirect(reverse('checker:incorrect'))

    return render(request, 'checker/checker.html')


def correct(request):
    return render(request, 'checker/correct.html')


def incorrect(request):
    return render(request, 'checker/incorrect.html')

baronbale_website/baronbale_website/downloads/views.py
from django.shortcuts import render

from .models import Cache


def downloads(request, cache_id):
    render_context = dict()
    render_context['id'] = cache_id

    cache = Cache.objects.get(cache_id=cache_id)
    if cache is None:
        render_context['errors'] = [_('Cache not found.')]
    else:
        render_context['name'] = cache.name
        render_context['downloads'] = cache.get_all_images()

    return render(request, 'downloads/downloads.html')


def create_downloads(request):
    pass

baronbale_website/baronbale_website/gc_toolbox/views/BannerCollectorView.py
import traceback
import datetime
import logging
import os
import shutil
import tempfile

from django.core import mail
from django.urls import reverse_lazy
from django.utils.translation import ugettext as _
from django.views.generic import FormView

from baronbale_website.common import exceptions, message_utils
from baronbale_website.gc_toolbox import banner_parser, banner_sorter
from baronbale_website.gc_toolbox.forms import UploadGPXForm
from baronbale_website.gc_toolbox.tools.banner_utils import extract_gpx_if_needed, join_banners

logger = logging.getLogger('django')

BANNERS_SESSION_KEY = 'banners'
TIMER_SESSION_KEY = 'banner_timer'
TIMER_FORMAT = '%d.%m.%Y %H:%M%S'


class BannerCollectorView(FormView):
    template_name = 'gc_toolbox/banner_collector.html'
    form_class = UploadGPXForm
    success_url = reverse_lazy('gc_toolbox:banner_collector')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        session = self.request.session
        if session:
            banners = session.get(BANNERS_SESSION_KEY, None)
            session[BANNERS_SESSION_KEY] = None
            if banners:
                context['banner'] = banners
        return context

    def form_valid(self, form):
        self.request.session[TIMER_SESSION_KEY] = datetime.datetime.utcnow().strftime(TIMER_FORMAT)
        uploaded_file = form.cleaned_data['banner_file']
        horizontal_banners_per_row = form.cleaned_data['horizontal_banners_per_row']
        vertical_banners_per_row = form.cleaned_data['vertical_banners_per_row']
        try:
            gpx_files = extract_gpx_if_needed(uploaded_file)
            banners = self.parse_banners(gpx_files)
            self.put_banners_to_session(banners, horizontal_banners_per_row, vertical_banners_per_row)
        except exceptions.BaronBaleException as e:
            message_utils.add_error_message(self.request.session, str(e))
            logger.error('Error while parsing banners', e)
        except Exception:
            self.handle_error()
        finally:
            shutil.rmtree(os.path.join(tempfile.gettempdir(), uploaded_file.name), ignore_errors=True)
        return super().form_valid(form)

    def handle_error(self):
        message_utils.add_error_message(self.request.session, _(
            'While parsing your banners an error occurred. The admin has been informed, please come back later.'))
        error_text = traceback.format_exc()
        logger.error(error_text)
        mail.mail_admins('An error occurred while parsing banners!', error_text)

    def parse_banners(self, gpx_files):
        banners = banner_parser.collect_banner_urls(gpx_files, self.request.session)
        banners = banner_sorter.sort_banner(banners)
        return banners

    def put_banners_to_session(self, banners, horizontal_banners_per_row, vertical_banners_per_row):
        joined_banners = join_banners(banners, horizontal_banners_per_row, vertical_banners_per_row)
        joined_banners += '<p>' + _(
            'The bannerlist was generated on') + ' <a href="https://baronbale.de/tools/gc/banner/">baronbale.de</a></p>'
        self.request.session[BANNERS_SESSION_KEY] = joined_banners
        self.log_duration()

    def log_duration(self):
        start_time = datetime.datetime.strptime(self.request.session.pop(TIMER_SESSION_KEY), TIMER_FORMAT)
        now = datetime.datetime.utcnow()
        duration = now - start_time
        logger.info('Parsing banners took {}'.format(duration))

baronbale_website/baronbale_website/homepage/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'homepage/index.html')

baronbale_website/baronbale_website/initializer/views.py
from django.shortcuts import render

# Create your views here.

baronbale_website/baronbale_website/lab/views.py
from django.http import HttpResponse
from django.shortcuts import render

import certifi, json, urllib3
import calendar
from datetime import datetime

DOMAIN = "https://grobbo.de"
PORT_KITCHEN = "9996"
PORT_LIVING_ROOM = "9995"
DATETIMEFORMAT = "%d.%m.%Y %H:%M %z"


def index(request):
    humidity = fetch_json(temp=False)
    temp = fetch_json(humidity=False)
    return render(request, 'lab/index.html', {'data_humidity_liv': humidity['Wohnzimmer']['data'],
                                              'data_humidity_kit': humidity['K\udcc3che']['data'],
                                              'data_temperature_liv': temp['Wohnzimmer']['data'],
                                              'data_temperature_kit': temp['K\udcc3che']['data']})


def display_json(request):
    json_dict = fetch_json(humidity=False)
    return HttpResponse(json.dumps(json_dict))


def fetch_json(temp=True, humidity=True):
    http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
    server_request = http.request('GET', '{}:{}'.format(DOMAIN, PORT_LIVING_ROOM))
    json_dict = json.loads(server_request.data.decode('utf-8'))
    server_request = http.request('GET', '{}:{}'.format(DOMAIN, PORT_KITCHEN))
    json_dict.update(json.loads(server_request.data.decode('utf-8', 'replace')))
    if not temp:
        return strip_temperature(json_dict)
    if not humidity:
        return strip_humidity(json_dict)
    return json_dict


def strip_temperature(json_dict):
    return strip_from_index(json_dict, 2)


def strip_humidity(json_dict):
    return strip_from_index(json_dict, 1)


def strip_from_index(json_dict, index):
    new_dict = {}
    for key, value in json_dict.items():
        value_list = []
        for dataset in value:
            date = datetime.strptime(dataset[0], DATETIMEFORMAT)
            plot_date = calendar.timegm(date.timetuple()) * 1000 + 3600000
            value_list += [[plot_date, dataset[index]]]
        new_dict[key] = {'label': key, 'data': value_list[-144:]}
    return new_dict

baronbale_website/baronbale_website/staticpages/views.py
from django.views.generic.base import TemplateView


class Contribute(TemplateView):
    template_name = 'staticpages/contribute.html'


class Imprint(TemplateView):
    template_name = 'staticpages/imprint.html'


class PrivacyPolicy(TemplateView):
    template_name = 'staticpages/privacy.html'


class Roadmap(TemplateView):
    template_name = 'staticpages/roadmap.html'

baronbale_website/baronbale_website/toolbox/views.py
from django.shortcuts import render

from .forms import DuplicateRemoverForm
from .tools.duplicate_remover import clear_duplicates


def duplicate_remover(request):
    if request.method == 'POST':
        form = DuplicateRemoverForm(request.POST)
        if form.is_valid():
            new_items = form.cleaned_data['new_items']
            old_items = form.cleaned_data['old_items']
            result = clear_duplicates(new_items, old_items)
            result['duplicate_items'] = ', '.join(result['duplicate_items'])
            result['unique_items'] = ', '.join(result['unique_items'])
            result_context = {
                'form': form,
                'result': result
            }
        else:
            result_context = {'form': DuplicateRemoverForm()}
    else:
        result_context = {'form': DuplicateRemoverForm()}

    return render(request, 'toolbox/duplicate_remover.html', result_context)

baronbale_website/baronbale_website/templates/base.html
<!DOCTYPE html>
{% load static i18n messaging %}
<html>
    <head>
        <title>baronbale.de - {% block title %}{% endblock %}</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="follow, all" />
        {% block meta %}{% endblock meta %}

        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/big.css' %}" media="screen and (min-width: 800px)"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/small.css' %}" media="all and (max-width: 799px)" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/tiny.css' %}" media="all and (max-width: 330px)" />
        {% block link %}{% endblock link %}

        <script src="{% static '/js/jquery.js' %}"></script>
        <script src="{% static '/js/code.js' %}"></script>
        {% block script %}{% endblock script %}
    </head>
    <body>
        <header>
            <nav class="nav_bar">
                <a href="/" id="logo_home"><img src="{% static 'img/logo.png' %}" alt="baronbale.de" title="baronbale.de" id="logo" /></a>
                <label for="drop" class="toggle">Menu</label>
                <input type="checkbox" id="drop" />
                <ul class="menu">
					<li><a href="/">{% trans 'Home' %}</a></li>
					<li>
						<label for="drop-1" class="toggle">{% trans 'GC-Tools' %} +</label>
						<a href="#">{% trans 'GC-Tools' %}</a>
						<input type="checkbox" id="drop-1"/>
						<ul>
							<li><a href="{% url 'gc_toolbox:banner_collector' %}">{% trans 'Banner Collector' %}</a></li>
							<li><a href="{% url 'gc_toolbox:base64' %}">{% trans 'base64' %}</a></li>
							<li><a href="{% url 'gc_toolbox:cesar' %}">{% trans 'Cesar Cipher' %}</a></li>
							<li><a href="{% url 'gc_toolbox:lettervalues' %}">{% trans 'Lettervalues' %}</a></li>
							<li><a href="{% url 'gc_toolbox:polybius' %}">{% trans 'Polybius Cipher' %}</a></li>
						</ul>
					</li>
                    <li>
                        <label for="drop-2" class="toggle">{% trans 'Tools' %} +</label>
                        <a href="#">{% trans 'Tools' %}</a>
                        <input type="checkbox" id="drop-2" />
                        <ul>
                            <li><a href="{% url 'toolbox:duplicate_remover' %}">{% trans 'Duplicate Remover' %}</a></li>
                        </ul>
                    </li>
					<li><a href="{% url 'staticpages:contribute' %}">{% trans 'Contribute' %}</a></li>
                </ul>
            </nav>
        </header>
        <main>
        {% get_error_messages request.session as error_messages %}
        {% if error_messages %}
            <div class="errorlist">
                <ul>
                    {% for error_message in error_messages %}
                        <li>{{ error_message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% block breadcrumbs %}{% endblock %}
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <div id="sidebar">
            {% block sidebar %}{% endblock %}
        </div>
        </main>
        <footer id="pagefooter">
            <a href="{% url 'staticpages:imprint' %}">{% trans "Imprint" %}</a> |
            <a href="{% url 'staticpages:privacy' %}">{% trans "Privacy Policy and Cookies" %}</a> |
            <a href="ed.elabnorab@elab:otliam" id="contact">{% trans 'Contact us' %}</a>

            {% block footer_links %}{% endblock footer_links %}
            {% comment %}
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}" />
                <select name="language" onchange="this.form.submit()">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
            </form>
            {% endcomment %}
        </footer>

    <script type="application/javascript">
        var mail_to = document.getElementById("contact");
        var href = mail_to.getAttribute("href");
        mail_to.setAttribute("href", href.split("").reverse().join(""));
    </script>
    </body>
</html>