baronbale_website/baronbale_website/gc_toolbox/urls.py
from django.conf.urls import url

from . import views_cesar, views_polybius, views_lettervalues, views_base64
from .views import BannerCollectorView

app_name = 'gc_toolbox'
urlpatterns = [
    url(r'^base64/$', views_base64.index, name='base64'),
    url(r'^base64/encode/file/$', views_base64.encode_file, name='base64_encode_file'),
    url(r'^base64/encode/text/$', views_base64.encode_text, name='base64_encode_text'),
    url(r'^base64/decode/$', views_base64.decode, name='base64_decode'),

    url(r'^cesar/$', views_cesar.index, name='cesar'),
    url(r'^cesar/encrypt/$', views_cesar.encrypt, name='cesar_encrypt'),
    url(r'^cesar/decrypt/$', views_cesar.decrypt, name='cesar_decrypt'),

    url(r'^lettervalues/$', views_lettervalues.letter_value_calculator, name='lettervalues'),

    url(r'^polybius/$', views_polybius.index, name='polybius'),
    url(r'^polybius/encrypt/$', views_polybius.encrypt, name='polybius_encrypt'),
    url(r'^polybius/decrypt/$', views_polybius.decrypt, name='polybius_decrypt'),

    url(r'banner/$', BannerCollectorView.BannerCollectorView.as_view(), name="banner_collector"),
]

baronbale_website/baronbale_website/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

urlpatterns = i18n_patterns(
    url(r'^tools/gc/', include('baronbale_website.gc_toolbox.urls')),
    url(r'^tools/', include('baronbale_website.toolbox.urls')),
    url(r'^', include('baronbale_website.homepage.urls')),
    url(r'^o_pulchram_avem/', include('baronbale_website.checker.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('baronbale_website.staticpages.urls'))
)

urlpatterns += [
                   url(r'^i18n/', include('django.conf.urls.i18n')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'staticpages.views.error404'

baronbale_website/baronbale_website/gc_toolbox/models.py
from django.db import models


class CacheCoordinates(models.Model):
    gc_code = models.CharField(max_length=10)
    latitude = models.CharField(max_length=15)
    longitude = models.CharField(max_length=15)
    type = models.CharField(max_length=30, null=True)

    class Meta:
        unique_together = (('gc_code', 'latitude', 'longitude'),)


class BannerDimension(models.Model):
    banner = models.CharField(max_length=64)
    ratio = models.FloatField(default=0.0)
    width = models.IntegerField()
    height = models.IntegerField()


class SpecialBanner(models.Model):
    gc_code = models.CharField(max_length=10)
    image_url = models.CharField(max_length=255, null=True, blank=True)
    reason = models.CharField(max_length=100)

    def __str__(self):
        return self.gc_code

baronbale_website/baronbale_website/gc_toolbox/forms.py
from django.utils.translation import ugettext as _
from django import forms


def get_cesar_cipher_choices(include_all):
    choices = []
    if include_all:
        choices += [(0, _('all'))]
    for idx in range(1, 26):
        choices += [(idx, idx)]
    return choices


class CesarCipherEncryptForm(forms.Form):
    plain_message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )

    key = forms.ChoiceField(
        label=_('Key'),
        choices=get_cesar_cipher_choices(False),
        initial=13
    )


class CesarCipherDecryptForm(forms.Form):
    cipher_message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )

    key = forms.ChoiceField(
        label=_('Key'),
        choices=get_cesar_cipher_choices(True),
        initial=0
    )


class PolybiusCipherForm(forms.Form):
    message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )


class LetterValueCalculatorForm(forms.Form):
    options = (
        ('1', 'A=01, ..., Z=26'),
        ('2', 'A=26, ..., Z=01'),
    )

    message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )

    extra_values = forms.CharField(
        label=_('Extra Values'),
        widget=forms.Textarea,
        required=False
    )

    direction = forms.ChoiceField(
        label=_('Direction'),
        choices=options
    )

    offset = forms.IntegerField(
        label=_('Offset'),
        initial=0
    )

    include_numeric = forms.BooleanField(
        label=_('Include numeric values'),
        required=False
    )


class Base64EncodeFileForm(forms.Form):
    file_to_encode = forms.FileField(
        label=_('File to encode')
    )


class Base64EncodeTextForm(forms.Form):
    message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )


class Base64DecodeForm(forms.Form):
    message = forms.CharField(
        label=_('Message'),
        widget=forms.Textarea
    )

    is_file = forms.BooleanField(
        label=_('Is a file'),
        required=False
    )


class UploadGPXForm(forms.Form):
    banner_file = forms.FileField(
        label=_('GPX- or zip-File')
    )
    horizontal_banners_per_row = forms.IntegerField(
        label=_('Horizontal banners per row'),
        min_value=1,
        initial=2
    )
    vertical_banners_per_row = forms.IntegerField(
        label=_('Vertical banners per row'),
        min_value=1,
        initial=3
    )

baronbale_website/baronbale_website/gc_toolbox/views/BannerCollectorView.py
import traceback
import datetime
import logging
import os
import shutil
import tempfile

from django.core import mail
from django.urls import reverse_lazy
from django.utils.translation import ugettext as _
from django.views.generic import FormView

from baronbale_website.common import exceptions, message_utils
from baronbale_website.gc_toolbox import banner_parser, banner_sorter
from baronbale_website.gc_toolbox.forms import UploadGPXForm
from baronbale_website.gc_toolbox.tools.banner_utils import extract_gpx_if_needed, join_banners

logger = logging.getLogger('django')

BANNERS_SESSION_KEY = 'banners'
TIMER_SESSION_KEY = 'banner_timer'
TIMER_FORMAT = '%d.%m.%Y %H:%M%S'


class BannerCollectorView(FormView):
    template_name = 'gc_toolbox/banner_collector.html'
    form_class = UploadGPXForm
    success_url = reverse_lazy('gc_toolbox:banner_collector')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        session = self.request.session
        if session:
            banners = session.get(BANNERS_SESSION_KEY, None)
            session[BANNERS_SESSION_KEY] = None
            if banners:
                context['banner'] = banners
        return context

    def form_valid(self, form):
        self.request.session[TIMER_SESSION_KEY] = datetime.datetime.utcnow().strftime(TIMER_FORMAT)
        uploaded_file = form.cleaned_data['banner_file']
        horizontal_banners_per_row = form.cleaned_data['horizontal_banners_per_row']
        vertical_banners_per_row = form.cleaned_data['vertical_banners_per_row']
        try:
            gpx_files = extract_gpx_if_needed(uploaded_file)
            banners = self.parse_banners(gpx_files)
            self.put_banners_to_session(banners, horizontal_banners_per_row, vertical_banners_per_row)
        except exceptions.BaronBaleException as e:
            message_utils.add_error_message(self.request.session, str(e))
            logger.error('Error while parsing banners', e)
        except Exception:
            self.handle_error()
        finally:
            shutil.rmtree(os.path.join(tempfile.gettempdir(), uploaded_file.name), ignore_errors=True)
        return super().form_valid(form)

    def handle_error(self):
        message_utils.add_error_message(self.request.session, _(
            'While parsing your banners an error occurred. The admin has been informed, please come back later.'))
        error_text = traceback.format_exc()
        logger.error(error_text)
        mail.mail_admins('An error occurred while parsing banners!', error_text)

    def parse_banners(self, gpx_files):
        banners = banner_parser.collect_banner_urls(gpx_files, self.request.session)
        banners = banner_sorter.sort_banner(banners)
        return banners

    def put_banners_to_session(self, banners, horizontal_banners_per_row, vertical_banners_per_row):
        joined_banners = join_banners(banners, horizontal_banners_per_row, vertical_banners_per_row)
        joined_banners += '<p>' + _(
            'The bannerlist was generated on') + ' <a href="https://baronbale.de/tools/gc/banner/">baronbale.de</a></p>'
        self.request.session[BANNERS_SESSION_KEY] = joined_banners
        self.log_duration()

    def log_duration(self):
        start_time = datetime.datetime.strptime(self.request.session.pop(TIMER_SESSION_KEY), TIMER_FORMAT)
        now = datetime.datetime.utcnow()
        duration = now - start_time
        logger.info('Parsing banners took {}'.format(duration))

baronbale_website/baronbale_website/gc_toolbox/templates/gc_toolbox/banner_collector.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Banner collector' %}{% endblock %}
{% block content %}
    <h1>{% trans 'Banner collector' %}</h1>

    <p>
        {% blocktrans trimmed %}
            At first a big thank you to Cetacea91, Daxianer, LaMulder and martl for their feedback and for providing
            test data!
        {% endblocktrans %}
    </p>
    <h2>Feedback willkommen!</h2>
    <p>
        Hey, der Banner-Parser wird nicht schlecht genutzt. Deswegen und weil er doch ein paar Macken hat habe ich mich
        entschlossen, eine neue Version zu schreiben in der ich all die Erfahrung dieser ersten Version einfließen
        lasse. Wenn Du Feedback hast, das unbedingt in die nächste Version einfließen sollte lass es mich wissen!
        Schreibe mir einfach eine Mail an <a href="mailto:protux@baronbale.de">protux@baronbale.de</a>!
    </p>
    <p>
        Bisher ist geplant, die Suche asynchron laufen zu lassen, sodass klarer ist, dass ihr warten müsst. Im
        Optimalfall soll eine Abschätzung abgegeben werden wie lange es dauern wird die Banner zu parsen. Außerdem
        soll es möglich sein fälschlicherweise erkannte Banner und Banner und Banner die nicht mehr beim Hoster
        verfügbar sind zu filtern.
    </p>
    <p>
        Wenn dich am aktuellen Parser etwas stört oder es Funktionen gäbe welche dir das Leben vereinfachen würden sag
        Bescheid. 😎
    </p>

    <p>{% trans 'This tools takes the gpx file with your found caches and collects the banners from the listings.' %}</p>
    <p>{% trans 'The banners are parsed from the "long_description" and for some special cases and for generating the link-tags we need the GC-Code and the url.' %}</p>
    <p>{% trans 'IMPORTANT: Since we also rearrange the banners for a more beautiful shape we need to get the size of all images, that could take a while, please be patient.' %}</p>

    <h2>{% trans 'How to use this tool' %}</h2>
    <p>
        {% blocktrans trimmed %}
            You can either upload a single GPX-file (like the "my finds" file) or you can directly upload the zip file
            you get from Groundspeak. If you are not a premium member you can collect all GPX-Files of the caches you
            found manually and put them in a single zip. You can then upload this zip file and the tool will look into
            all of the contained GPX files and will collect all the banners from those who have one.
        {% endblocktrans %}
    </p>
    <form method="POST" action="{% url 'gc_toolbox:banner_collector' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Collect Banner' %}"/>
    </form>

    {% if banner %}
        <h1>{% trans 'Your banners' %}</h1>
        <form style="display: block;">
            <textarea style="display: block; width: 100%; min-height: 25em;">{{ banner }}</textarea>
        </form>
    {% endif %}

    <h2>{% trans 'I found a bug or the tool behaves funny' %}</h2>
    <p>
        {% blocktrans trimmed %}
            If you found a bug, or you know, the tool does not find a banner please contact me. I cannot test with all
            caches and some banners are pretty hard to catch. You can find the contact email in the footer and in the
            imprint. It would be great, if you could provide the GPX or zip-file which triggered the wrong behaviour.
        {% endblocktrans %}
    </p>
    <p>
        {% blocktrans trimmed %}
            If you have any question or proposal for improvement we can also talk about it, of course.
        {% endblocktrans %}
    </p>
{% endblock content %}

baronbale_website/baronbale_website/gc_toolbox/templates/gc_toolbox/base64.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Base64 En-/Decoder' %}{% endblock %}
{% block content %}
<h1>{% trans 'Base64 En-/Decoder' %}</h1>
<p>{% trans 'This tool helps you to en- and decode base64. You can encode text or whole files.' %}</p>

<h2>{% trans 'Encode file' %}</h2>
<p>{% trans 'If you encode a file it will be read byte by byte and then the bytes will be encoded. No files are saved on the server pemanently, in order to process them they need to be saved temporarily but they will be deleted before you download begins.' %}</p>
<form action="{% url 'gc_toolbox:base64_encode_file' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ encode_file_form.as_p }}
    <input type="submit" value="{% trans 'Encode' %}" />
</form>

<h2>{% trans 'Encode text' %}</h2>

<form action="{% url 'gc_toolbox:base64_encode_text' %}" method="POST">
    {% csrf_token %}
    {{ encode_text_form.as_p }}
    <input type="submit" value="{% trans 'Encode' %}" />
</form>

<h2>{% trans 'Decode' %}</h2>
<p>{% trans 'To decode files you need to paste the base64 encoded file into the inputfield and check the "is file" field. Your file will then be decoded and offered to download.' %}</p>
<form action="{% url 'gc_toolbox:base64_decode' %}" method="POST">
    {% csrf_token %}
    {{ decode_form.as_p }}
    <input type="submit" value="{% trans 'Decode' %}" />
</form>
{% endblock %}

baronbale_website/baronbale_website/gc_toolbox/templates/gc_toolbox/cesar_cipher.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Cesar Cipher' %}{% endblock %}
{% block content %}
<h1>{% trans 'Cesar-Cipher' %}</h1>
<p>{% trans 'Cesar-Cipher is an encryption method where the message is encrypted by rotating the lettervalues between 1 and 25.' %}</p>

<div>
    <h2>{% trans 'Encryption' %}</h2>
    <form method="POST" action="{% url 'gc_toolbox:cesar_encrypt' %}">
        {% csrf_token %}
        {{ encrypt_form.as_p }}
        <input type="submit" value="{% trans 'Encrypt' %}" />
    </form>
</div>

<div id="decryption">
    <h2>{% trans 'Decryption' %}</h2>
    <form method="POST" action="{% url 'gc_toolbox:cesar_decrypt' %}">
        {% csrf_token %}
        {{ decrypt_form.as_p }}
        <input type="submit" value="{% trans 'Decrypt' %}" />
    </form>
</div>
{% endblock %}

baronbale_website/baronbale_website/gc_toolbox/templates/gc_toolbox/letter_value.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Letter Value Calculator' %}{% endblock %}

{% block content %}
<h1>{% trans 'Letter Value Calculator' %}</h1>

<p>{% trans 'This tool takes a text and calculates the value of its letters. Every sign which is not a-z or A-Z will be ignored. You can provide additional values in the "extra values" field. If you tick the "Include numeric values" field the numbers 0-9 are included with their adherent value.' %}</p>
<p>
    {% trans 'You can also define own sign/ value pairs. Just type [sign]\=[value] into the "extra values" field.' %}<br/>
    {% trans 'Example' %}: !:=100<br/>
    {% trans 'Multiple extra values need to be seperated by a line break.' %}<br/> 
    {% trans 'Example' %}:<br/>
    !:=100<br/>
    ?:=-20
</p>

{% if result %}
<ul>
    <li>{% trans 'Letter value' %}: {{ result.total_value }}</li>
    <li>{% trans 'Total signs' %}: {{ result.total_signs }}</li>
    <li>{% trans 'Sum of digits' %}: {{ result.sum_of_digits }}</li>
    <li>{% trans 'Iterated sum of digits' %}: {{ result.iterated_sum_of_digits }}</li>
    <li>{% trans 'Number of relevant signs' %}: {{ result.relevant_signs }}</li>
    <li>{% trans 'Number of letters' %}: {{ result.letters }}</li>
    <li>{% trans 'Number of numbers' %}: {{ result.numbers }}</li>
    <li>{% trans 'Number of special characters' %}: {{ result.special_characters }}</li>
    <li>{% trans 'Values of relevant signs' %}: {{ result.relevant_values }}</li>
</ul>
{% endif %}

<form action="{% url 'gc_toolbox:lettervalues' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans 'Calculate Lettervalues' %}" />
</form>
{% endblock %}

baronbale_website/baronbale_website/gc_toolbox/templates/gc_toolbox/polybius.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Polybius-Cipher' %}{% endblock %}

{% block content %}
<h1>{% trans 'Polybius-Cipher' %}</h1>
<p>{% trans 'The Polybius encryption is another encryption named after a guy long gone. It was invented 200 years before the cesar cipher but is much stronger than the cesar cipher. But it would not be here if this would not be needed for geocaching, so here it is. ' %}</p>

<h1 id="encrypt">{% trans 'Encrypt' %}</h1>
<form action="{% url 'gc_toolbox:polybius_encrypt' %}" method="POST">
	{% csrf_token %}
	{{ encrypt_form.as_p }}
	<input type="submit" value="{% trans 'Encrypt' %}" />
</form>

<h1 id="decrypt">{% trans 'Decrypt' %}</h1>
<form action="{% url 'gc_toolbox:polybius_decrypt' %}" method="POST">
	{% csrf_token %}
	{{ decrypt_form.as_p }}
	<input type="submit" value="{% trans 'Decrypt' %}" />
</form>
{% endblock %}