baronbale_website/baronbale_website/checker/urls.py
from django.conf.urls import url

from . import views

app_name = 'checker'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^correct$', views.correct, name='correct'),
    url(r'^incorrect$', views.incorrect, name='incorrect'),
]

baronbale_website/baronbale_website/staticpages/urls.py
from django.conf.urls import url

from . import views

app_name = 'staticpages'
urlpatterns = [
    url(r'contribute/$', views.Contribute.as_view(), name='contribute'),
    url(r'imprint/$', views.Imprint.as_view(), name='imprint'),
    url(r'privacy/$', views.PrivacyPolicy.as_view(), name='privacy'),
    url(r'roadmap/$', views.Roadmap.as_view(), name='roadmap'),
]

baronbale_website/baronbale_website/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin

urlpatterns = i18n_patterns(
    url(r'^tools/gc/', include('baronbale_website.gc_toolbox.urls')),
    url(r'^tools/', include('baronbale_website.toolbox.urls')),
    url(r'^', include('baronbale_website.homepage.urls')),
    url(r'^o_pulchram_avem/', include('baronbale_website.checker.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('baronbale_website.staticpages.urls'))
)

urlpatterns += [
                   url(r'^i18n/', include('django.conf.urls.i18n')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'staticpages.views.error404'

baronbale_website/baronbale_website/checker/models.py
from django.db import models

# Create your models here.

baronbale_website/baronbale_website/checker/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def index(request):
    if request.method == 'POST':

        checker_code = request.POST.get('ccode')
        checker_code = checker_code.strip().lower()
        if checker_code == 'h gis fis e fis gis' or checker_code == "h'' gis'' fis'' e'' fis'' gis''" or checker_code == 'h" gis" fis" e" fis" gis"':
            return HttpResponseRedirect(reverse('checker:correct'))
        else:
            return HttpResponseRedirect(reverse('checker:incorrect'))

    return render(request, 'checker/checker.html')


def correct(request):
    return render(request, 'checker/correct.html')


def incorrect(request):
    return render(request, 'checker/incorrect.html')

baronbale_website/baronbale_website/checker/templates/checker/checker.html
{% extends 'checker/checker_base.html' %}
{% load i18n %}
{% block title %}O pulchram avem! - Vor Ort Checker{% endblock %}
{% block content %}
<h1>O pulchram avem! - Vor Ort Checker</h1>
<p>
    Hier könnt ihr überprüfen, ob ihr bereit seid euch mit Calimero zu unterhalten.
</p>

<form method="POST" action="{% url 'checker:index' %}">
    {% csrf_token %}
    <p>
        <label for="ccode">Welche Noten musst du Calimero vorspielen? (Trenne einzelne Noten mit einem Leerzeichen)</label>
        <input type="text" id="ccode" name="ccode">
    </p>
    <input type="submit">
</form>
{% endblock %}

baronbale_website/baronbale_website/checker/templates/checker/checker_base.html
<!DOCTYPE html>
{% load static i18n %}
<html>
    <head>
        <title>baronbale.de - {% block title %}{% endblock %}</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="follow, all" />
        {% block meta %}{% endblock meta %}

        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/big.css' %}" media="screen and (min-width: 800px)"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/small.css' %}" media="all and (max-width: 799px)" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/tiny.css' %}" media="all and (max-width: 330px)" />
        {% block link %}{% endblock link %}

        <script src="{% static '/js/jquery.js' %}"></script>
        <script src="{% static '/js/code.js' %}"></script>
        {% block script %}{% endblock script %}
    </head>
    <body>
        <header>
            <nav class="nav_bar">
                <a href="/" id="logo_home"><img src="{% static 'img/logo.png' %}" alt="baronbale.de" title="baronbale.de" id="logo" /></a>
            </nav>
        </header>
        <main>
        {% block breadcrumbs %}{% endblock %}
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <div id="sidebar">
            {% block sidebar %}{% endblock %}
        </div>
        </main>
        <footer id="pagefooter">
            <a href="{% url 'staticpages:imprint' %}">{% trans "Imprint" %}</a> |
            <a href="{% url 'staticpages:privacy' %}">{% trans "Privacy Policy and Cookies" %}</a>

            {% block footer_links %}{% endblock footer_links %}

            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}" />
                <select name="language" onchange="this.form.submit()">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
            </form>
        </footer>
    </body>
</html>

baronbale_website/baronbale_website/checker/templates/checker/correct.html
{% extends 'checker/checker_base.html' %}
{% load i18n %}
{% block title %}O pulchram avem! - Vor Ort Checker{% endblock %}
{% block content %}
<h1>O pulchram avem! - Vor Ort Checker</h1>
<p>Jawohl! Das war korrekt! Jetzt geh bitte und schau wie es Calimero geht, vielen Dank.</p>
{% endblock %}

baronbale_website/baronbale_website/checker/templates/checker/incorrect.html
{% extends 'checker/checker_base.html' %}
{% load i18n %}
{% block title %}O pulchram avem! - Vor Ort Checker{% endblock %}
{% block content %}
<h1>O pulchram avem! - Vor Ort Checker</h1>
<p>Nein, das war leider falsch, so wird das mit der Kommunikation mit Calimero nichts. :(</p>
{% endblock %}